service: legion

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  stage: dev
  region: us-east-1
  memorySize: 256
  vpc: # vpc-70658509 | EQ-DC-Tunnel
    securityGroupIds:
      - sg-081b437d # api-gateway-dc
    subnetIds:
      - subnet-b59ae9fe # EQ-DC-Lambda Public 1A
      - subnet-df12bb82 # EQ-DC-Lambda Public 1B

functions:
  legion:
    handler: app.handler
    environment:
      SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
      SLACK_OVERLORD_WEBHOOK: ${env:SLACK_OVERLORD_WEBHOOK}
      SLACK_SNOKE_WEBHOOK: ${env:SLACK_SNOKE_WEBHOOK}
      VID_COMP_API: ${env:VID_COMP_API}
      GITHUB_TOKEN: ${env:GITHUB_TOKEN}
      NETLIFY_TOKEN: ${env:NETLIFY_TOKEN}
      SNOKE_MAINT_BUILD_HOOK: ${env:SNOKE_MAINT_BUILD_HOOK}
      OVERLORD_MAINT_BUILD_HOOK: ${env:OVERLORD_MAINT_BUILD_HOOK}
      YELP_API_KEY: ${env:YELP_API_KEY}
      PGHOST: ${env:PGHOST}
      PGDATABASE: ${env:PGDATABASE}
      PGUSER: ${env:PGUSER}
      PGPASSWORD: ${env:PGPASSWORD}
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
