service: legion

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 300
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  legion:
    handler: app.handler
    environment:
      AUTH_JWT: ${env:AUTH_JWT}
      SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
      SLACK_VERIFY_TOKEN: ${env:SLACK_VERIFY_TOKEN}
      SLACK_OVERLORD_WEBHOOK: ${env:SLACK_OVERLORD_WEBHOOK}
      SLACK_SNOKE_WEBHOOK: ${env:SLACK_SNOKE_WEBHOOK}
      VID_COMP_API: ${env:VID_COMP_API}
      WL_SEG_API: ${env:WL_SEG_API}
      SNOKE_MAINT_BUILD_HOOK: ${env:SNOKE_MAINT_BUILD_HOOK}
      OVERLORD_MAINT_BUILD_HOOK: ${env:OVERLORD_MAINT_BUILD_HOOK}
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
